config/routes.rb
Rails.application.routes.draw do
  
  resources :recipes
  resources :questions
  resources :surveys
  resources :guests
  resources :welcome
  resources :events
  resources :challenges

  devise_for :users
  resources :users

  
  root 'welcome#index'

  resources :events do
    member do
      post :toggle_participation
      post :toggle_status
      post :abort_status
    end
  end

  resources :challenges do
    member do
      get :upd
      post :upd
      put :upd
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :challenges, through: :events
  has_many :surveys, foreign_key: 'surveyor_id', class_name: "Survey"

  validates :username, presence: true

  #after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success] = "Un futur chef (trivialement appelé un user) vient d'être créé."
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = "Des modifications ont été apportées aux informations concernant l'utilisateur et ça c'est plutôt bien passé."
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      flash[:success] = "Eh Féfé, on vient de perdre un user!"
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_challenge.html.erb
  <div class="mb-5">
      <div>
        <h4>Mes Challenges</h4>
      </div>
  </div>

  <div class="row">

    <% @challenges = @user.challenges %>

    <% @challenges.each do |challenge| %>

    
      <% @events = challenge.events %>

      <% @my_event = Event.where(user_id: current_user.id, challenge_id: challenge.id)[0].id %>
      
      <div class="col-lg-6">
        <div class="bs-component">
          <div class="list-group mb-3">
            <a href="/events/<%= @my_event %>"  class="list-group-item list-group-item-action flex-column align-items-start active">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 gray-text"><%= challenge.title %></h5>
                <% if challenge.status == "ongoing" %>
                  <span class="badge bg-light text-sm-start green-text Regular shadow">EN COURS</span>
                <% elsif challenge.status == "pending" %>
                  <span class="badge bg-light text-sm-start Small shadow">en attente</span>
                <% elsif challenge.status == "abort" %>
                  <span class="badge bg-warning text-sm-start gray-text">annulé</span>
                <% elsif challenge.status == "finish" %>
                  <span class="badge bg-dark text-sm-start">terminé</span>
                <% end %>
              </div>

              <p class="mb-1"><span class="small">Thème : </span><span class="gray-text"><%= challenge.meal_category %></span></p>
            </a>
    

            <a href="/events/<%= @my_event %>" class="list-group-item list-group-item-action flex-column align-items-start">
              <div class="d-flex w-100 justify-content-between mb-2">
                <h6 class="mb-1">Participants</h6>
              </div>
              <% @events.each do |event| %>
                <div class="d-flex justify-content-between">
                  <div class="d-flex justify-content-start">

                    <div class="mr-3">
                      <% if event.participation == "pending" %>
                        <span class=""><i class="fa fa-check-circle" style="color:lightgray"></i></span>
                      <% elsif event.participation == "confirmed" %>
                        <span class="red-text"><i class="fa fa-check-circle"></i></span>
                      <% elsif event.participation == "abort" %>
                        <span class=""><i class="fa fa-ban" style="color:lightgray"></i></span>
                      <% end %>
                    </div>
                    <div>
                      <%= event.user.username.capitalize %>
                    </div>
                  </div>
                  <div>
                    <% if challenge.status == "finish" && event == Event.where(challenge_id: challenge.id).order("total_event DESC").first %>
                      <%= image_tag "chief.png", :class => "winner-logo" %>
                    <% end %>
                  </div>
                  <div>
                    <% if event.role == "créateur" %>
                      <span class="badge bg-light text-dark"><%= event.role %></span>
                    <% elsif event.role == "participant" &&  event.participation == "pending" %>
                      <span class="text-muted small font-weight-light font-italic">en attente</span>
                    <% elsif event.role == "participant" &&  event.participation == "confirmed" %>
                      <span class="badge bg-light text-dark"><%= event.role %></span>
                    <% elsif event.role == "décliné" %>
                      <span class="badge bg-warning text-dark"><%= event.role %></span>
                    <% end %>
                  </div>
                </div>
              <% end %>
              
              <hr>
              <small class="text-muted">Message du créateur :</small>
              <p class="font-weight-light"><%= challenge.description %></p>
            </a>
          </div>
        </div>
      </div>
    <% end %>
    
  </div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> a empêché l'enregistrement de cet utilisateur</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_no-challenge.html.erb
<div class="card mb-3 user">
  <div class="row g-0">
    <div class="col-md-4 card-img">
      <%= image_tag "ustensile.jpg", :class => "img-card" %>
    </div>
    <div class="col-md-8 card-text">
      <div class="card-body">

        <div class="d-flex align-items-start flex-column bd-highlight mb-3" style="height: 200px;">
          <div class="p-2 bd-highlight">
            <h2>Salut <%= @user.username.capitalize %></h2>
          </div>
          <div class="p-2 bd-highlight ">
            <h3 class="card-title red-text mb-4">Bienvenue sur ton espace</h3>
            <p>Pour l'instant tu ne participes à aucun challenge.<br>Souhaites-tu créer ton premier Cooking Challenge ?</p>
          </div>
          <div class="mt-auto p-2 bd-highlight">
            <div>
              <%= link_to 'Créer un challenge', new_challenge_path, :class => "btn btn-primary btn-lg" %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/_pending-challenge.html.erb
<div class="mb-5">
  <h4>Challenges en attentes</h4>
</div>

<div class="row p-1">
  <% @pending_challenges.each do |event| %>
    <div class="col-11">
      <div class="pl-2 pr-2 list-group-item">
        <% @event_creator = Event.where(challenge_id: event.challenge_id, role: "créateur").first %>
            <div class="mr-auto p-2">
              <h5><%= event.challenge.title %></h5>
              <span class="text-muted">invité par : <%= @event_creator.user.username %></span><br>
              <span class="text-muted">Thème : <%= event.challenge.theme_choice %> => <%= event.challenge.meal_category %><%= event.challenge.meal_area %></span>
            </div>
        <div class="d-flex align-items-center">
            <div class="p-2"><h5><span class=""><%= link_to 'Accepter', toggle_participation_event_path(id: event.id), method: 'post', :class => 'badge badge-primary' %></span></h5></div>
            <div class="p-2"><h5><span class=""><%= link_to 'Décliner', abort_status_event_path(id: event.id), method: 'post', :class => 'badge badge-warning' %></span></h5></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Modifier l'utilisateur</h1>

<%= render 'form', user: @user %>

<%= link_to 'Afficher', @user %> |
<%= link_to 'Retour', users_path %>

app/views/users/index.html.erb
<div class="container">

  <h1>Les utilisateurs</h1>


  <hr>
  <% if user_signed_in? %>
    <p>
      <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %> 
    </p>
  <% else %>
    <p>
      <%= link_to 'Se connecter', new_user_session_path %>  
    </p>
  <% end %>

  <hr>
  <%= link_to 'Créer un challenge', new_challenge_path, :class => "btn btn-primary btn-lg" %>

  <hr>


  <p>
    <span><strong>user_signed_in? : </strong><%= user_signed_in? %> </span>
  </p>
  <% if user_signed_in? %>
    <p>
      <strong>username : </strong><%= current_user.username %><br>
      <strong>email : </strong><%= current_user.email %><br>
      <strong>id : </strong><%= current_user.id %><br>
      <strong>user_session : </strong><%= user_session %> 
    </p>
  <% end %>



  <table>
    <thead>
      <tr>
        <th>email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= link_to 'Afficher', user %></td>
          <td><%= link_to 'Modifier', edit_user_path(user) %></td>
          <td><%= link_to 'Détruire', user, method: :delete, data: { confirm: 'Es-tu vraiment certain ?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nouvelle utilisateur', new_user_path %>

  <hr>

  <p>
    <%= debug user_signed_in? %>
  </p>

  <% if debug user_signed_in? %>
    <p>
      <span class="strong">current_user : <%= current_user %> </span>
    </p>
  <% end %>

  <p>
    <%= debug session.to_hash %>
  </p>

</div>

app/views/users/new.html.erb
<h1>Nouvel utilisateur</h1>

<%= render 'form', user: @user %>

<%= link_to 'Retour', users_path %>

app/views/users/show.html.erb
<div class="container mt-4">

<!-- If User has no challenge -->
  <% if @user.events.count == 0 %>
  <%= render 'users/no-challenge' %>
<!-- If User has challenge -->
  <% else %>

    <!-- User challenge pending -->
    <div class="row">
      <% @pending_challenges = Event.where(user_id: current_user.id, participation: "pending") %>
      <% if @pending_challenges.count != 0%>
        <div class="col-4">
          <%= render 'users/pending-challenge' %>
        </div>
      <% else%>
        <div class="col-0">
        </div>
      <% end %>


      <% if @pending_challenges.count != 0%>
      <div class="col-8">
        <%= render 'users/challenge', confirmed_events: @confirmed_events %>
      </div>
      <% else%>
      <div class="col-12">
        <%= render 'users/challenge', confirmed_events: @confirmed_events %>
      </div>
      <% end %>
    </div>


  
  <% end %>
</div>



<% if @user.events.count != 0 %>
<div class="container">
  <div class="p-5 d-flex justify-content-center">
    <div>
      <%= link_to 'créer un nouveau challenge', new_challenge_path, :class => "btn btn-primary btn-lg" %>
    </div>
  </div>

</div>
<% end %>

app/views/users/toggle_participation.js.erb
var challengeAll = document.getElementById("display")("<%= escape_javascript(render "book", book: @book) %>");
alert("book created");
console.log(challengeAll)