config/routes.rb
Rails.application.routes.draw do
  
  resources :recipes
  resources :questions
  resources :surveys
  resources :guests
  resources :welcome
  resources :events
  resources :challenges

  devise_for :users
  resources :users

  
  root 'welcome#index'

  resources :events do
    member do
      post :toggle_participation
      post :toggle_status
      post :abort_status
    end
  end

  resources :challenges do
    member do
      get :upd
      post :upd
      put :upd
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user
  belongs_to :challenge
  has_many :surveys, dependent: :destroy
  has_one :recipe, dependent: :destroy
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy toggle_participation toggle_status abort_status ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        flash[:success] = "Le diner a été créé."
        format.html { redirect_to @event }
        format.json { render :show, status: :created, location: @event }
      else
        flash.now[:danger] = "Echec :" + @event.errors.full_messages.join(" ")
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        flash[:success] = "Le dîner vient d'être modifié."
        format.html { redirect_to @event }
        format.json { render :show, status: :ok, location: @event }
      else
        flash.now[:warning] = "Echec :" + @event.errors.full_messages.join(" ")
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      flash[:danger] = "Le dîner vient d'être détruit."
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end


  def toggle_participation

    if @event.participation == "confirmed"
      @event.participation = "pending"
      @event.save
     
    elsif @event.participation == "abort"
      @event.participation = "confirmed"
      @event.save

    else
      @event.participation = "confirmed"
      @event.save
    end  
    event_status(@event)

    respond_to do |format|
      format.html  { redirect_to user_path(@event.user.id) }
      format.js { render user_path(@event.user.id) }
    end

  end


  def abort_status
    if @event.participation == "pending"
      @event.participation = "abort"
      @event.role = "décliné"
      @event.save
    end
    event_status(@event)

    respond_to do |format|
      format.html  { redirect_to user_path(@event.user.id) }
      format.js { render user_path(@event.user.id) }
    end

  end
  
  # change event status and create the needed number of survey matching the event
  def toggle_status

    @questions_list = [
      "Est ce que le plat est conforme au thème, à la recette ?", 
      "Est-ce que c'était bon ?", 
      "Est ce que l'hôte a apporté une touche personnel à la recette ?",
      "Quel note donneriez vous à la présentation ?"
    ]

    if @event.status == "unscheduled"
      @event.status = "done"
      @event.save
      flash.now[:success] = "Le dîner vient de se terminer. Alors c'était bon? A vos questionnaires"
      # défini le nombre de Survey à créer en comptant le nombre de participant moins le créateur participant de l'event actuel
      @event_survey = Event.where(challenge_id: @event.challenge_id).where.not(user_id: @event.user_id).to_a

      @event_survey.each_with_index do |survey, index|
        @new_survey = Survey.create(event_id: @event.id, surveyor_id: survey.user_id, challenge_id: @event.challenge_id )
          @questions_list.each do |question|
            @new_question = Question.create(survey_id: @new_survey.id, label: question)
          end
      end

    else
      @event.status = "unscheduled"
      @event.save
    end

    respond_to do |format|
      format.html  { redirect_to event_path(@event.id) }
      format.js { render event_path(@event.id) }
    end

  end




  def survey_question()

    @questions_list = [
      "est ce que le plat est conforme au thème, à la recette ?", 
      "est-ce que c'était bon ?", 
      "est ce que l'hôte a apporté une touche personnel à la recette ?",
      "quel note donneriez vous à la présentation ?"
    ]

    return @questions_list
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {})
    end
    
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_accordion.html.erb
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <!-- accordion PARTICIPATION line -->
        <div class="d-flex justify-content-between">
          <div  class="mr-3">
            <h5>Ma participation </h5>
          </div>
        </div>
        <div>
          <% if event.role == "créateur" %>
            <span class="badge bg-light text-dark"><%= event.role %></span>
          <% elsif event.role == "participant" &&  event.participation == "pending" %>
            <span class="badge bg-light font-italic">en attente</span>
          <% elsif event.role == "participant" &&  event.participation == "confirmed" %>
            <span class="badge bg-light green-text">confirmée</span>
          <% elsif event.role == "décliné" %>
            <span class="badge bg-warning text-dark"><%= event.role %></span>
          <% end %>
        </div>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <!-- render my participation info -->
        <%= render 'my-participation', event: @event %>
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <div>
          <h5>Etat du challenge </h5>
        </div>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <!-- render my participation info -->
        <%= render 'challenge-recap', event: @event %>
        
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        <h5>Ma recette </h5>
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <!-- render recipe -->
        <%= render 'full-recipe', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/_challenge-recap.html.erb
<!-- Liste des autres participants -->
<div class="">
  <% @this_event = Event.where(challenge_id: @event.challenge.id).where.not(user_id: current_user.id) %>
  <% @this_event.each do |event| %>
    <div class="row">
      <div class="col-md-8">
        <div class="d-flex justify-content-between">
          <div class="d-flex justify-content-start mb-4">
            <div class="mr-2">
              <% if event.participation == "pending" %><span class=""><i class="fa fa-check-circle" style="color:lightgray"></i></span>
              <% elsif event.participation == "confirmed" %><span class=""><i class="fa fa-check-circle" style="color:indianred"></i></span>
              <% else %><i class="fas fa-ban"></i>
              <% end %>
            </div>  
            <% if event.participation == "pending" %>
              <div>
                <span class="red-text"><%= event.user.username.capitalize %></span> n'a pas encore confirmé sa participation
              </div>
            <% elsif event.participation == "abord" %>
              <div>
                <span class="red-text"><%= event.user.username.capitalize %></span> a décliné le challenge
              </div>
            <%  elsif event.participation == "confirmed"  %>
              <div>
                <% if event.status == "unscheduled" %>
                  <span class="red-text"><%= event.user.username.capitalize %></span> n'a pas encore planifié son dîner
                <% elsif event.status == "scheduled" %>
                  <span class="red-text"><%= event.user.username.capitalize %></span> : son dîner est programmé
                <% elsif event.status == "done" %>
                  Le dîner de <span class="red-text"><%= event.user.username.capitalize %></span> est passé, c'est evalution time
                  <!--  -->
                  <% @surveys = event.surveys %>
                  <% @currentUser_survey = Survey.where(event_id: event.id, surveyor_id: current_user.id)[0] %>
                  <div class="card mt-2 p-2">
                    <% if @currentUser_survey.created_at == @currentUser_survey.updated_at %>
                      <div class="row">
                        <div class="col-md-9 text-muted small">
                          Tu ne pourras voir la note des autres participants qu'après avoir compléter ton évalution.
                        </div>
                        <div class="col-md-3">
                          <%= link_to "Noter", edit_survey_path(@currentUser_survey), :class => "btn btn-outline-primary btn-sm p-1" %>
                        </div>
                      </div> 
                    <% else %>
                      <% @surveys.each do |survey| %>

                        <div class="p-1 pl-2">
                          <% if survey.created_at != survey.updated_at %>
                            <% if current_user.id == survey.surveyor_id %>
                              <div>tu as donnée la note de : <%= survey.total_grade %></div>
                            <% else %>
                              <div><%= survey.surveyor.username %> a donnée la note de : <%= survey.total_grade %></div>
                            <% end %>
                          <% else %>
                            <div><%= survey.surveyor.username %> n'a pas encore noté</div>
                          <% end %>
                        </div>

                      <% end %>
                    <% end %>
                  </div>

                <% end %>
              </div> 
            <% end %>
          </div>
        </div>
      </div>


      <div class="col-md-4">
        <% if event.surveys.any? { |el| el.status == "pending" } == true %>
          <div class="gray-text text-center">
            Note provisoire : <%= event.total_event %>
          </div>
        <% elsif event.surveys.count == 0 %>
          <div class="gray-text text-center">
           
          </div>
        <% else %>
          <div class="green-text text-center">
            Score final est <%= event.total_event %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> a empêché l'enregistrement decet événement :</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_full-recipe.html.erb
<% @event %>

<div class="">
  <div class="d-flex justify-content-between">
    <div class="pl-3">
      <h3><%=  @event.recipe.meal %></h3>
      <div class="">
        <p>categorie : <span class="red-text"><%=  @event.recipe.category %></span>  - origine : <span class="red-text"><%=  @event.recipe.area %></span> - tags : <span class="red-text"><%= @event.recipe.tags %></span> 
        </p>
      </div>
    </div>
    <div class="mr-3">
      <% if @event.recipe.youtube != "" %>
        <a href="<%= @event.recipe.youtube %>" target="_blank">
        <img alt="youtube" class="youtube-link" mouseover="branchen_personalber_mo.png" src="/assets/008-youtube.svg">
        </a>
      <% end%>
    </div>
  </div>

  <div class="d-flex flex-row p-3">
    <div class="">
      <img src="<%=  @event.recipe.mealThumb %>" alt="<%=  @event.recipe.meal %>" class="recipe-picture">
    </div>
    <div class="recipe-ingredient">
      <ul>
        <% if @event.recipe.ingredient1  != "" %>
          <li><%=  @event.recipe.ingredient1 %> : <%=  @event.recipe.measure1 %></li>
        <% end %>

        <% if @event.recipe.ingredient2  != "" %>
          <li><%=  @event.recipe.ingredient2 %> : <%=  @event.recipe.measure2 %></li>
        <% end %>

        <% if @event.recipe.ingredient3  != "" %>
          <li><%=  @event.recipe.ingredient3 %> : <%=  @event.recipe.measure3 %></li>
        <% end %>

        <% if @event.recipe.ingredient4  != "" %>
          <li><%=  @event.recipe.ingredient4 %> : <%=  @event.recipe.measure4 %></li>
        <% end %>

        <% if @event.recipe.ingredient5  != "" %>
          <li><%=  @event.recipe.ingredient5 %> : <%=  @event.recipe.measure5 %></li>
        <% end %>

        <% if @event.recipe.ingredient6  != "" %>
          <li><%=  @event.recipe.ingredient6 %> : <%=  @event.recipe.measure6 %></li>
        <% end %>

        <% if @event.recipe.ingredient7  != "" %>
          <li><%=  @event.recipe.ingredient7 %> : <%=  @event.recipe.measure7 %></li>
        <% end %>

        <% if @event.recipe.ingredient8  != "" %>
          <li><%=  @event.recipe.ingredient8 %> : <%=  @event.recipe.measure8 %></li>
        <% end %>

        <% if @event.recipe.ingredient9  != "" %>
          <li><%=  @event.recipe.ingredient9 %> : <%=  @event.recipe.measure9 %></li>
        <% end %>

        <% if @event.recipe.ingredient10  != "" %>
          <li><%=  @event.recipe.ingredient10 %> : <%=  @event.recipe.measure10 %></li>
        <% end %>
      </ul>

    </div>
    <div class="recipe-ingredient">
      <ul>
        <% if @event.recipe.ingredient11  != "" %>
          <li><%=  @event.recipe.ingredient11 %> : <%=  @event.recipe.measure11 %></li>
        <% end %>

        <% if @event.recipe.ingredient12  != "" %>
          <li><%=  @event.recipe.ingredient12 %> : <%=  @event.recipe.measure12 %></li>
        <% end %>

        <% if @event.recipe.ingredient13  != "" %>
          <li><%=  @event.recipe.ingredient13 %> : <%=  @event.recipe.measure13 %></li>
        <% end %>

        <% if @event.recipe.ingredient14  != "" %>
          <li><%=  @event.recipe.ingredient14 %> : <%=  @event.recipe.measure14 %></li>
        <% end %>

        <% if @event.recipe.ingredient15  != "" %>
          <li><%=  @event.recipe.ingredient15 %> : <%=  @event.recipe.measure15 %></li>
        <% end %>

        <% if @event.recipe.ingredient16  != "" %>
          <li><%=  @event.recipe.ingredient16 %> : <%=  @event.recipe.measure16 %></li>
        <% end %>

        <% if @event.recipe.ingredient17  != "" %>
          <li><%=  @event.recipe.ingredient17 %> : <%=  @event.recipe.measure17 %></li>
        <% end %>

        <% if @event.recipe.ingredient18  != "" %>
          <li><%=  @event.recipe.ingredient18 %> : <%=  @event.recipe.measure18 %></li>
        <% end %>

        <% if @event.recipe.ingredient19  != "" %>
          <li><%=  @event.recipe.ingredient19 %> : <%=  @event.recipe.measure19 %></li>
        <% end %>

        <% if @event.recipe.ingredient20  != "" %>
          <li><%=  @event.recipe.ingredient20 %> : <%=  @event.recipe.measure20 %></li>
        <% end %>
      </ul>

    </div>
  </div>
    
    <div class="col-12">
      <div class="recipe-instruction">
        <p><span class="red-text">instructions :</span> <%=  @event.recipe.instructions %></p>
      </div>
    </div>
    

</div>

app/views/events/_my-participation.html.erb
<!-- info du current_user à propos du challenge -->
<div class="">
  <!-- role creator -->
  <% if @event.role == "créateur" %>
    <h6 class="card-subtitle text-muted mb-2">En tant que créateur du challenge ta partipation est confirmée</h6>
    <%= render 'participation-confirmed', event: @event %>
  <!-- role participant - status pending -->
  <% elsif @event.role == "participant" && @event.participation == "pending" %>

    <h6 class="card-subtitle text-muted mb-2">ma participation est : <%= @event.participation %>. Souhaites tu confirmer ta participation :</h6>
    <%= link_to 'accepter', toggle_participation_event_path, method: 'post', :class => 'badge badge-primary badge-pill' %><br>
    <%= link_to 'décliner', abort_status_event_path, method: 'post', :class => 'badge badge-warning badge-pill' %>
    
  <!-- role participant - status confirmed -->
  <% elsif @event.role == "participant" && @event.participation == "confirmed" %>

    <h6 class="card-subtitle text-muted mb-2">ta participation est confirmée</h6>
    <%= render 'participation-confirmed', event: @event %>
    
  <!-- status abort -->
  <% elsif @event.participation == "abort" %>

    <h6 class="card-subtitle text-muted mb-2">Tu as choisis de ne pas participer</h6>
    <% if @event.challenge.status == "pending" %>
      <p>Le challenge n'a pas encore commencé, il n'est pas encore possible de changer d'avis ou valider ta participation</p>
      <%= link_to 'participer', toggle_participation_event_path, method: 'post', :class => 'badge badge-primary badge-pill' %>
    <% else %>
      <p>Le challenge est débuté. Ce n'est plus possible d'y participer. Veux tu créer le tien !</p>
      <div>
        <%= link_to 'créer ton challenge', new_challenge_path, :class => "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  
  <% end %> 
</div>

app/views/events/_participation-confirmed.html.erb
<% if @event.status == "unscheduled" %>
  <p>
    tu n'as pas encore planifié ton dîner.
  </p>
  <p>
    <%= link_to 'VALIDER MON DINER', toggle_status_event_path, method: 'post', :class => 'btn btn-outline-primary'%>
  </p>

<% elsif @event.status == "done" %>
  <p>
    Félicitation ! Tu as réalisé ton challenge. Voyons ce que les autres ont pensé de ta prestation ...
  </p>

  <h6 class="card-subtitle text-muted mb-2">Ma notation : </h6>
  
    <div class="row">
      <div class="col-md-9">
 
          <% @event_surveys = @event.surveys %>
          <% @other_surveys = Survey.where(event_id: @event.id).where.not(surveyor_id: current_user.id) %>
          <% @other_surveys.each do |survey| %>
              <% if survey.status == "pending" %>
                <div><span class="red-text"><%= survey.surveyor.username.capitalize %></span> ne t'as pas encore noté</div>
              <% elsif survey.status == "done" %>
                <div>
                  <div class=""><span class="red-text"><%= survey.surveyor.username.capitalize %></span> t'as donné la note de <span class="red-text"> <%= survey.total_grade %></span></div>
                  <div class="ml-3 mb-2">
                    <% if survey.comment == nil || survey.comment == "" %><span class="gray-text text-muted font-italic">pas de commentaires</span></li>
                    <% else %><span class="text-muted red-text">Son commentaire : </span><span class="gray-text text-muted font-italic"><%= survey.comment %></span>
                    <% end %>
                  </div>
                </div>
              <% end %>

          <% end %>

      </div>

      <div class="col-md-3">
        <% @other_surveys = Survey.where(event_id: @event.id).where.not(surveyor_id: current_user.id) %>
        <% if @other_surveys.count == 0 %>
          <div class="gray-text text-center">
           
          </div>
        <% elsif @other_surveys.all? { |el| el.status == "pending" } == true %>
          <div class="gray-text text-center">
            
          </div>

        <% elsif @other_surveys.any? { |el| el.status == "pending" } == true %>
          <div class="gray-text text-center">
            Ma note provisoire : <%= @event.total_event %>
          </div>

        <% elsif @other_surveys.all? { |el| el.status == "done" } == true %>
          <div class="green-text text-center">
            mon Score final est <%= @event.total_event %>
          </div>
        <% end %>
      </div>

    </div>                     
  <% end %>

app/views/events/edit.html.erb
<h1>Modifier le dîner</h1>

<%= render 'form', event: @event %>

<%= link_to 'Afficher', @event %> |
<%= link_to 'Retour', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dîner</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to 'Afficher', event %></td>
        <td><%= link_to 'Modifier', edit_event_path(event) %></td>
        <td><%= link_to 'Détruire', event, method: :delete, data: { confirm: 'Es-tu vraiment certain ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau dîner', new_event_path %>

app/views/events/new.html.erb
<h1>Nouveau dîner</h1>

<%= render 'form', event: @event %>

<%= link_to 'Retour', events_path %>

app/views/events/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <% if Event.where(user_id: current_user.id).where.not(challenge_id: @event.challenge.id).count == 0 %>
    <div class="col-lg-12">
    <% else %>
    <div class="col-lg-8">
    <% end %>
<!--- Challenge info-->
      <div class="bs-component">
        <div class="card mb-3">
          <!---header-->
          <div class="card-header d-flex w-100 justify-content-between">
            <h2 class="mb-1 text-muted"><%= @event.challenge.title.upcase %></h2>
            <div>
              <% if @event.challenge.status == "ongoing" %>
                <h3><span class="badge bg-light text-sm-start green-text Regular shadow">EN COURS</span></h3>
              <% elsif @event.challenge.status == "pending" %>
                <h3><span class="badge bg-light text-sm-start Small shadow">en attente</span></h3>
              <% elsif @event.challenge.status == "abort" %>
                <h3><span class="badge bg-warning text-sm-start gray-text">annulé</span></h3>
              <% elsif @event.challenge.status == "finish" %>
                <h3><span class="badge bg-dark white-text text-sm-start">terminé</span></h3>
              <% end %>
            </div>
          </div>
          <!---Info challenge-->
          <div class="card-body header-event">
            <div class="row">
              <div class="col-5">
                <% if @event.challenge.theme_choice = "Category" %>
                <h5 class="card-title mb-4">Category du challenge : <span class="red-text"><%= @event.challenge.meal_category %></span></h5>
                <% else %>
                <h5 class="card-title mb-4">Pays du challenge : <span class="red-text"><%= @event.challenge.meal_area %></span></h5>
                <% end %>
                <h6 class="card-subtitle text-muted">message du créateur :</h6>
                <p class="pt-2"><%= @event.challenge.description %></p>
              </div>
              <div class="col-7">
                <% @all_events = Event.where(challenge_id: @event.challenge_id).order(total_event: :desc) %>
                <% if @event.challenge.status == "ongoing" %>
                  <div>
                    <table class="table-sm mb-2">
                      <% @all_events.each do |event| %>
                        <tr class="score">
                          <td style="width:100px"><%= event.user.username.capitalize %></td>
                          <td><%= event.total_event %></td>
                        </tr>
                      <% end %>
                    </table>
                  </div>
                 
                <% elsif @event.challenge.status == "finish" %>
                  <% @all_events = Event.where(challenge_id: @event.challenge_id).count %>
                  <div class="row">
                    <div class="col-3">
                      <%= image_tag "chief.png", :class => "winner-pic" %>
                    </div>
                    <div class="col-9">
                      <% @event_winner = Event.where(challenge_id: @event.challenge.id).order("total_event DESC").first %>
                      <h5 class="card-title"><span class="red-text"><%= @event_winner.user.username %></span></h5>
                      <h6>vainqueur avec une note de <%= Event.where(challenge_id: @event.challenge.id).maximum("total_event") %></h6>
                    </div>
                  </div>
                <% end %> 
              </div>
              
            </div>
          </div>

          <!---Accordion display-->
          <div>
            <%= render 'accordion', event: @event %>
          </div>

          <!-- Card Footer -->
          <div class="card-footer text-muted">
            <p></p>
          </div>

        </div>
      </div>
    </div>

<!--Other current_user challenge-->
    <div class="col-lg-4">
      <div class="bs-component">
        <div class="list-group">
          <% @my_sessions = Event.where(user_id: current_user.id).where.not(challenge_id: @event.challenge.id) %>
          <% @my_sessions.each do |session| %>
            <a href="/events/<%= session.id %>" class="list-group-item list-group-item-action">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><%= session.challenge.title %></h5>
                <div>
                  <% if session.challenge.status == "ongoing" %>
                    <span class="badge bg-light text-sm-start green-text Regular shadow">EN COURS</span>
                  <% elsif session.challenge.status == "pending" %>
                    <span class="badge bg-light text-sm-start Small shadow">en attente</span>
                  <% elsif session.challenge.status == "abort" %>
                    <span class="badge bg-warning text-sm-start gray-text">annulé</span>
                  <% elsif session.challenge.status == "finish" %>
                    <span class="badge bg-light text-sm-start Small shadow">terminé</span>
                  <% end %>
                </div>
              </div>
              <div></div>
            </a>
          <% end %>
        </div>
      </div>
    </div>

          
  </div>
</div>