config/routes.rb
Rails.application.routes.draw do
  
  resources :recipes
  resources :questions
  resources :surveys
  resources :guests
  resources :welcome
  resources :events
  resources :challenges

  devise_for :users
  resources :users

  
  root 'welcome#index'

  resources :events do
    member do
      post :toggle_participation
      post :toggle_status
      post :abort_status
    end
  end

  resources :challenges do
    member do
      get :upd
      post :upd
      put :upd
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/survey.rb
class Survey < ApplicationRecord

  belongs_to :event
  belongs_to :surveyor, class_name: "User"

  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy update_event_total ]

  # GET /surveys or /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        flash.now[:success] = "Création du questionaire."
        format.html { redirect_to @survey}
        format.json { render :show, status: :created, location: @survey }
      else
        flash.now[:danger] = "Echec :" + @survey.errors.full_messages.join(" ")
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        # calcul et save le total de tous les questions> grades
        @sum = @survey.questions.all.sum(:grade)
        @survey.total_grade = @sum
        @survey.status = "done"
        @survey.save
        
        # update le total de l'event, la note global - somme des surveys 
        update_event_total()
        event_status(@survey.event)
        flash[:success] = "Le questionnaire vient d'être mis à jour."
        format.html { redirect_to event_path(@survey.event_id) } 
        format.json { render :show, status: :ok, location: @survey }
      else
        flash.now[:warning] = "Echec :" + @survey.errors.full_messages.join(" ")
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Le questionnaire vient d'être détruit." }
      format.json { head :no_content }
    end
  end

  def update_event_total
    @event = @survey.event
    @total = @event.surveys.all.sum(:total_grade)
    @event.total_event = @total
    @event.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:id, :comment, questions_attributes: [:id, :label, :grade])
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_with(model: survey) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> a empêché l'enregistrement de ce questionnaire :</h2>

      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/_question_fields.html.erb
<p>
  <%= f.text_field :label, class: 'form-control', readonly: true %><br>

  <div class="d-flex justify-content-around">
    <div>
      <%= f.radio_button :grade, 1, class: 'mr-3' %>
      <%= f.label :grade, 1 %>
    </div>

    <div>
      <%= f.radio_button :grade, 2, class: 'mr-3' %>
      <%= f.label :grade, 2 %>
    </div>

    <div>
      <%= f.radio_button :grade, 3, class: 'mr-3' %>
      <%= f.label :grade, 3 %>
    </div>

    <div>
      <%= f.radio_button :grade, 4, class: 'mr-3' %>
      <%= f.label :grade, 4 %>
    </div>

    <div>
      <%= f.radio_button :grade, 5, class: 'mr-3' %>
      <%= f.label :grade, 5 %>
    </div>
  </div>
</p>

app/views/surveys/_survey-recipe.html.erb
<% @survey %>
<% @event = @survey.event %>

<div class="">
  <div class="pl-3">
    <div class="d-flex justify-content-between">
      <div>
        <div>
          <h3><%=  @event.recipe.meal %></h3>
        </div>
        <div class="">
          <p>categorie : <span class="red-text"><%=  @event.recipe.category %></span>  - origine : <span class="red-text"><%=  @event.recipe.area %></span> - tags : <span class="red-text"><%= @event.recipe.tags %></span> 
          </p>
        </div>
      </div>
      <div class="mr-3">
        <% if @event.recipe.youtube != "" %>
          <a href="<%= @event.recipe.youtube %>" target="_blank">
          <img alt="youtube" class="youtube-link" mouseover="branchen_personalber_mo.png" src="/assets/008-youtube.svg">
          </a>
        <% end%>
      </div>
    </div>
  </div>

  <div class="d-flex flex-column">
    <div class="col-12">
      <div class="recipe-instruction">
        <p  class="text-justify"><img src="<%=  @event.recipe.mealThumb %>" alt="<%=  @event.recipe.meal %>" class="recipe-pic">
          <span class="red-text">instructions :</span>
          <%=  @event.recipe.instructions %>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-6">
        <div class="recipe-ingredient">
          <ul>
            <% if @event.recipe.ingredient1  != "" %>
              <li><%=  @event.recipe.ingredient1 %> : <%=  @event.recipe.measure1 %></li>
            <% end %>
            <% if @event.recipe.ingredient2  != "" %>
              <li><%=  @event.recipe.ingredient2 %> : <%=  @event.recipe.measure2 %></li>
            <% end %>
            <% if @event.recipe.ingredient3  != "" %>
              <li><%=  @event.recipe.ingredient3 %> : <%=  @event.recipe.measure3 %></li>
            <% end %>
            <% if @event.recipe.ingredient4  != "" %>
              <li><%=  @event.recipe.ingredient4 %> : <%=  @event.recipe.measure4 %></li>
            <% end %>
            <% if @event.recipe.ingredient5  != "" %>
              <li><%=  @event.recipe.ingredient5 %> : <%=  @event.recipe.measure5 %></li>
            <% end %>
            <% if @event.recipe.ingredient6  != "" %>
              <li><%=  @event.recipe.ingredient6 %> : <%=  @event.recipe.measure6 %></li>
            <% end %>
            <% if @event.recipe.ingredient7  != "" %>
              <li><%=  @event.recipe.ingredient7 %> : <%=  @event.recipe.measure7 %></li>
            <% end %>
            <% if @event.recipe.ingredient8  != "" %>
              <li><%=  @event.recipe.ingredient8 %> : <%=  @event.recipe.measure8 %></li>
            <% end %>
            <% if @event.recipe.ingredient9  != "" %>
              <li><%=  @event.recipe.ingredient9 %> : <%=  @event.recipe.measure9 %></li>
            <% end %>
            <% if @event.recipe.ingredient10  != "" %>
              <li><%=  @event.recipe.ingredient10 %> : <%=  @event.recipe.measure10 %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-6">
        <div class="recipe-ingredient">
          <ul>
            <% if @event.recipe.ingredient11  != "" %>
              <li><%=  @event.recipe.ingredient11 %> : <%=  @event.recipe.measure11 %></li>
            <% end %>
            <% if @event.recipe.ingredient12  != "" %>
              <li><%=  @event.recipe.ingredient12 %> : <%=  @event.recipe.measure12 %></li>
            <% end %>
            <% if @event.recipe.ingredient13  != "" %>
              <li><%=  @event.recipe.ingredient13 %> : <%=  @event.recipe.measure13 %></li>
            <% end %>
            <% if @event.recipe.ingredient14  != "" %>
              <li><%=  @event.recipe.ingredient14 %> : <%=  @event.recipe.measure14 %></li>
            <% end %>
            <% if @event.recipe.ingredient15  != "" %>
              <li><%=  @event.recipe.ingredient15 %> : <%=  @event.recipe.measure15 %></li>
            <% end %>
            <% if @event.recipe.ingredient16  != "" %>
              <li><%=  @event.recipe.ingredient16 %> : <%=  @event.recipe.measure16 %></li>
            <% end %>
            <% if @event.recipe.ingredient17  != "" %>
              <li><%=  @event.recipe.ingredient17 %> : <%=  @event.recipe.measure17 %></li>
            <% end %>
            <% if @event.recipe.ingredient18  != "" %>
              <li><%=  @event.recipe.ingredient18 %> : <%=  @event.recipe.measure18 %></li>
            <% end %>
            <% if @event.recipe.ingredient19  != "" %>
              <li><%=  @event.recipe.ingredient19 %> : <%=  @event.recipe.measure19 %></li>
            <% end %>
            <% if @event.recipe.ingredient20  != "" %>
              <li><%=  @event.recipe.ingredient20 %> : <%=  @event.recipe.measure20 %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/surveys/edit.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col-md-1">
      <%= image_tag "survey.png", class: 'survey-icon' %>
    </div>
    <div class="col-md-11">
      <div class="p-2">
        <h3>Questionnaire</h3>
        <p class="mt-4">
          <h5><%= @survey.surveyor.username.capitalize %> l'heure est venue de noter la prestation de <%= @survey.event.user.username.capitalize%></h5>
        </p>
      </div>
    </div>
  </div>
  <div>
    <p class="red-text ml-2">
      <small>La graduation va de 1, la plus basse, mauvaise note à 5 la plus haute, la meilleure note.</small><br>
      <small>Afin de mieux pouvoir juger le dîner de <%= @survey.event.user.username.capitalize%>, sa recette est présentée sur la droite.</small>
    </p>
  </div>

  <div class="row">
    <div class="col-md-6">

      <%= form_for @survey do |f| %>
    
        <%= f.fields_for :questions do |builder| %>
          <%= render "question_fields", :f => builder %>

        <% end %>

        <p class="text-muted">
          Tu peux aussi laisser un commentaire, un remerciement à <%= @survey.event.user.username.capitalize%>. Cela ne rapporte pas de points mais c'est toujours sympa.
        </p>
        <%= f.text_area :comment, class: 'form-control'%><br>

        <div class="d-flex flex-row justify-content-around">
          <div class="p-2"><%= link_to 'Show', @survey %></div>
          <div class="p-2"><%= link_to 'Back', surveys_path %></div>
          <div class="p-2"><%= f.submit "Je soumets mon vote", class: 'btn btn-outline-primary' %></div>
        </div>

        <p></p>

      <% end %>
  
    </div>
    <div class="col-md-6">
      <%= render 'survey-recipe', survey: @survey %>
    </div>

  </div>
  

</div>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Les questionnaires</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to 'Afficher', survey %></td>
        <td><%= link_to 'Modifier', edit_survey_path(survey) %></td>
        <td><%= link_to 'Détruire', survey, method: :delete, data: { confirm: 'Es-tu vraiment certain ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau questionnaire', new_survey_path %>

app/views/surveys/new.html.erb
<h1>Nouveau questionnaire</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Retour', surveys_path %>

app/views/surveys/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <h3>Questionnaire</h3>

  <p class="mt-4">
    <%= @survey.surveyor.username.capitalize %> note la prestation de <%= @survey.event.user.username.capitalize%>
  </p>

  <% @questions = @survey.questions %>
  <% @questions.each do |question| %>

    <div class="card mb-2 p-2 col-6">
      <p><%= question.label %> <strong><%= question.grade %></strong></p>
    </div>
  <% end %>
  
  <div class="mb-3">
    <% if @survey.created_at == @survey.updated_at %>
      <h5><%= @survey.surveyor.username.capitalize %> n'a pas encore remplie ce questionnaire</h5>
    <% else %>
      <h5>La note total est de <%= @survey.total_grade %></h5>
    <% end %>
  </div>

  <%= link_to 'Modifier', edit_survey_path(@survey) %> |
  <%= link_to 'Retour', surveys_path %>

</div>